### ISSUE TITLE
Can't download on Windows: ERROR: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by fireattack** [kamikat/bilibili-get#9] opened 2018-08-17 04:22 UTC
```
C:\Users\Administrator>where aria2c
d:\program files\!cli\aria2c.exe

C:\Users\Administrator>where ffmpeg
C:\ProgramData\chocolatey\bin\ffmpeg.exe

C:\Users\Administrator>bilibili-get https://www.bilibili.com/video/av29332332
extracting video metadata...
[1/1] av29332332: start download "某伊藤姓高颜值特摄女饭庆生活动现场 伊藤美来201
7生日live"...
[1/1] av29332332: video quality:
[1/1] av29332332:     74      flv720_p60     高清 720P60
[1/1] av29332332:     64      flv720         高清 720P
[1/1] av29332332:   * 32      flv480         清晰 480P
[1/1] av29332332:     15      flv360         流畅 360P
[1/1] av29332332: output format: flv
[1/1] av29332332: output path:
[1/1] av29332332:     C:\Users\Administrator\av29332332 某伊藤姓高颜值特摄女饭庆
生活动现场(1) 伊藤美来2017生日live.flv
[1/1] av29332332: downloading video segment 1/8...
[1/1] av29332332: downloading video segment 2/8...
[1/1] av29332332: downloading video segment 3/8...
[1/1] av29332332: downloading video segment 4/8...
[1/1] av29332332: downloading video segment 5/8...
[1/1] av29332332: downloading video segment 6/8...
[1/1] av29332332: downloading video segment 7/8...
[1/1] av29332332: downloading video segment 8/8...
[1/1] av29332332: merging segment files...
ERROR: ENOENT: no such file or directory, unlink 'C:\Users\Administrator\av29332
332-1.flv'
```

**Comment by cleverpig** [comment] 2018-11-25 04:12
mark

**Comment by catright** [comment] 2019-02-03 09:12
can not reproduce this issue. please check the directory which files are actually downloaded.
if you use anti-virus program or ransom protection, they would prevent from modifying your files under C:\Users.

**Comment by shinonomeiro** [comment] 2019-02-23 07:08
Windows 7 user here.

This issue should be already fixed by now thanks to #14, which is likely why you couldn't reproduce it. However for some obscure reason, executing `npm i -g bilibili-get` on my machine fetches the old versions of the files where the downloader subprocess never gets spawned, so the merger miserably fails to find the expected files hence this error.

I've checked my package.json and it does say `bilibili-get@1.5.1`, but the files are from an earlier version. Any clue? Or might just as well manually overwrite the files.

**Comment by kamikat** [comment] 2019-02-25 04:19
#14 is not merged in 1.5.1

It's scheduled for 1.6.0

**Comment by shinonomeiro** [comment] 2019-02-25 06:23
Oh I see. Just noticed indeed that 1.5.1 was released in October while #14 only got fixed a month later. My mistake 😅. Thanks for the head-up! Looking forward to the next release of this awesome tool.

**Comment by kamikat** [comment] 2019-02-25 07:10
#14 introduces a filename quote issue needs to be fixed before next release.

**Comment by Z-zzy** [comment] 2019-04-10 14:30
Hi. I just meet the same problem. Looking forward to the 1.6.0.

**Closed as completed** 2019-05-30 06:30 UTC
Labels: question
